# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tradesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Dono_da_loja", models.CharField(max_length=14)),
                ("Nome_loja", models.CharField(max_length=19)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
