# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="cnabModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Tipo", models.CharField(max_length=1)),
                ("Data", models.CharField(max_length=10)),
                ("Valor", models.FloatField()),
                ("CPF", models.CharField(max_length=11)),
                ("Cartão", models.CharField(max_length=12)),
                ("Hora", models.CharField(max_length=8)),
                (
                    "trades",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnab",
                        to="trades.tradesmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
